Task 1: Creating Arrays

1. Write a Python program to:
o Create a 1D NumPy array of 10 integers ranging from 1 to 10.

In [6]:
import numpy as np
arr1=np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


Create a 2D NumPy array of shape (3, 3) with integers from 1
to 9?

In [7]:
arr2=np.arange(1,10).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Create a 3D NumPy array with random floating-point numbers
of shape (3, 5, 3)?

In [8]:
arr3=np.random.rand(3,5,3)
print(arr3)

[[[0.9959762  0.26421465 0.85935128]
  [0.17893099 0.65360583 0.83550095]
  [0.38635366 0.40526962 0.28384155]
  [0.94452545 0.85677529 0.88199555]
  [0.55482287 0.17604261 0.10989446]]

 [[0.92883112 0.51079998 0.7465701 ]
  [0.8730364  0.05924018 0.45336512]
  [0.51121717 0.81795211 0.14896026]
  [0.94295047 0.15114374 0.45471275]
  [0.62268857 0.4002325  0.42647069]]

 [[0.69668468 0.16497491 0.08543099]
  [0.30831762 0.67818634 0.29334624]
  [0.59055323 0.14241688 0.4537605 ]
  [0.82449975 0.31915454 0.22254312]
  [0.58623407 0.95325067 0.19541212]]]


2. Display the shape, size, and datatype of each array.

In [9]:
def display(name, arr):
    print(f"\n{name}:")
    print(arr)
    print(f"Shape: {arr.shape}")
    print(f"Size: {arr.size}")
    print(f"Datatype: {arr.dtype}")

# Display information for all arrays
display("1D Array", arr1)
display("2D Array", arr2)
display("3D Array", arr3)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Size: 10
Datatype: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Datatype: int64

3D Array:
[[[0.9959762  0.26421465 0.85935128]
  [0.17893099 0.65360583 0.83550095]
  [0.38635366 0.40526962 0.28384155]
  [0.94452545 0.85677529 0.88199555]
  [0.55482287 0.17604261 0.10989446]]

 [[0.92883112 0.51079998 0.7465701 ]
  [0.8730364  0.05924018 0.45336512]
  [0.51121717 0.81795211 0.14896026]
  [0.94295047 0.15114374 0.45471275]
  [0.62268857 0.4002325  0.42647069]]

 [[0.69668468 0.16497491 0.08543099]
  [0.30831762 0.67818634 0.29334624]
  [0.59055323 0.14241688 0.4537605 ]
  [0.82449975 0.31915454 0.22254312]
  [0.58623407 0.95325067 0.19541212]]]
Shape: (3, 5, 3)
Size: 45
Datatype: float64


Task 2: Array Indexing and Slicing

1. Create a NumPy array from the following list:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [10]:
data=[10, 20, 30, 40, 50, 60, 70, 80, 90]
arr=np.array(data)
print(arr)

[10 20 30 40 50 60 70 80 90]


2. Write a Python program to:
Retrieve the first three elements of the array.
Retrieve every alternate element of the array.
Reverse the array.
3. Perform the above operations and display the results

In [14]:
print(arr[:3])
print(arr[::2])
print(arr[::-1])

[10 20 30]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


Task 3: Mathematical Operations

1. Create two NumPy arrays, A and B, each with 5 random integers
between 1 and 20.
2. Write a Python program to:
- Add, subtract, multiply, and divide the two arrays elementwise.
- Compute the dot product of the arrays.
- Find the mean, median, standard deviation, and variance of
array A.
- Identify the maximum and minimum values in array B and
their indices.


In [16]:
a=np.random.randint(1,21,5)
b=np.random.randint(1,21,5)
print(a)
print(b)

[ 2  4 16 13 11]
[ 6 12 10 12  8]


In [17]:
print("\nAddition:", a+ b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [ 8 16 26 25 19]
Subtraction: [-4 -8  6  1  3]
Multiplication: [ 12  48 160 156  88]
Division: [0.33333333 0.33333333 1.6        1.08333333 1.375     ]


In [18]:
Dot_Product=np.dot(a,b)
print(Dot_Product)

464


In [19]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))

9.2
11.0
5.344155686354955
28.560000000000002


In [20]:
print(np.max(b),np.argmax(b))
print(np.min(b),np.argmin(b))

12 1
6 0


Task 4: Reshaping and Transposing

1. Create a 1D NumPy array of 12 integers ranging from 1 to 12.
2. Write a Python program to:
o Reshape the array into a 2D array of shape (4, 3).
o Reshape the array into a 3D array of shape (2, 2, 3).
o Transpose the reshaped 2D array and display its shape.

In [21]:
arr=np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
arr2=np.arange(1,13).reshape(4,3)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
arr3=np.arange(1,13).reshape(2,2,3)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [24]:
arr2=np.arange(1,13).reshape(4,3).T
print(arr2)

print(arr2.shape)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
(3, 4)


Task 5: Boolean Masking and Filtering

1. Create a NumPy array with 15 random integers between 10 and 50.
2. Write a Python program to:
- Find all elements greater than 25.
- Replace all elements less than 30 with 0.
- Count the number of elements divisible by 5.

In [25]:
arr=np.random.randint(10,51,15)
print(arr)

[10 15 12 45 46 27 16 50 50 36 47 15 15 28 35]


In [26]:
print(arr[arr>25])

[45 46 27 50 50 36 47 28 35]


In [27]:
arr2=arr.copy()
arr2[arr2<30]=0
print(arr2)

[ 0  0  0 45 46  0  0 50 50 36 47  0  0  0 35]


In [28]:
count=arr[(arr%5==0)&(arr!=0)]
print(count)
print(count.size)

[10 15 45 50 50 15 15 35]
8


Task 6: Working with Built-in Functions

1. Use NumPy's built-in functions to:
- Create an array of 10 equally spaced values between 0 and 1.
- Create an identity matrix of size 4x4.
- Generate a 1D array of 20 random integers between 1 and 100,
sort it, and find the 5 largest elements.

In [29]:
arr=np.linspace(0,1,10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [30]:
arr2=np.eye(4)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
arr3=np.random.randint(1,101,20)
print(arr3)

[91 69 22 38 30 90 54 25 15 51 57 16  1 24 77 82  5  9 70 90]


In [32]:
sorted=np.sort(arr3)
print(sorted)

[ 1  5  9 15 16 22 24 25 30 38 51 54 57 69 70 77 82 90 90 91]


In [33]:
print(sorted[-5:])

[77 82 90 90 91]


Task 7: Generic

1. Create a Python program that:
- Generates two large random arrays of size (100, 100).
- Performs matrix multiplication on the two arrays.
- Finds the determinant and inverse of the resulting matrix (if
possible).
- Measures the time taken to complete these operations.

In [36]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time

a = np.random.rand(100, 100)    #Two random arrays.
b = np.random.rand(100, 100)

start_time = time.time()
product = np.dot(a, b)   

#Matix Multiplication
Multiplication_time=time.time()-start_time
print("Product: ",product)
print(f"Matrix Multiplication is completed in {Multiplication_time:.4f} seconds.")
print()

start_time = time.time()
det=np.linalg.det(product)      

#Determinant of Matrix.
Determinant_time = time.time()-start_time
print("Determinant : ",det)
print(f"Time taken to calculate determinant is {Determinant_time:.4f} seconds")
print()

if np.isclose(det, 0):
    print("The Matrix is singular and cannot be inverted.")
else:
    start_time=time.time()
    inverse=np.linalg.inv(product)      #Inverse of Matrix.
    Inverse_time=time.time()-start_time
    print("Inverse: ",inverse)
    print(f"Time taken to calculate Inverse is {Inverse_time:.4f} seconds")
    print()




Product:  [[26.73350312 28.00603447 29.39305049 ... 29.20219078 29.81030501
  27.50201686]
 [27.1587882  27.33892268 29.39784512 ... 28.81323674 30.75214712
  28.60961151]
 [26.84520555 25.43949305 28.02526685 ... 27.66079258 30.14862827
  27.19978233]
 ...
 [26.5426202  25.61942729 27.3922348  ... 26.92629259 26.04042769
  24.59763851]
 [26.27342796 26.0648211  27.98064244 ... 29.08276753 29.56407601
  25.39513936]
 [25.39062261 25.68228499 25.81192464 ... 27.03038331 27.0602039
  24.32543841]]
Matrix Multiplication is completed in 0.0047 seconds.

Determinant :  -4.552805061255789e+51
Time taken to calculate determinant is 0.0009 seconds

Inverse:  [[ 0.80300963  1.50749006  0.24882822 ...  1.2389025   1.22657828
   0.5745288 ]
 [ 1.523656    1.86763042  0.19751908 ...  0.76315883  3.60038833
   1.55855481]
 [-0.92303806 -2.15236516 -1.11401562 ... -1.23101162 -2.71637042
  -1.22138142]
 ...
 [ 0.44574615  0.42541631  0.01431212 ...  0.17948714  0.11976272
   0.46231405]
 [-0.6495628